# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  api:
    build:
      context: "C:\\Users\\Fabia\\RiderProjects\\Backend"
      dockerfile: "Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Fabia\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Fabia\\RiderProjects\\Backend\\Api:/app:rw"
    - "C:\\Users\\Fabia\\RiderProjects\\Backend:/src:rw"
    working_dir: "/app"
