CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE sport (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    translations text[] NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('german', name)) STORED NOT NULL,
    CONSTRAINT pk_sport PRIMARY KEY (id)
);

CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    display_name text NOT NULL,
    email character varying(255),
    phone_number text,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    deleted_on timestamp with time zone NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE "group" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    sport_id bigint,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    deleted_on timestamp with time zone NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (id),
    CONSTRAINT fk_group_sport_sport_id FOREIGN KEY (sport_id) REFERENCES sport (id) ON DELETE SET NULL
);

CREATE TABLE training_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    session_date timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    location text,
    group_id bigint NOT NULL,
    CONSTRAINT pk_training_session PRIMARY KEY (id),
    CONSTRAINT fk_training_session_group_group_id FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE
);

CREATE TABLE user_group_membership (
    user_id bigint NOT NULL,
    group_id bigint NOT NULL,
    role integer NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    deleted_on timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_group_membership PRIMARY KEY (user_id, group_id),
    CONSTRAINT fk_user_group_membership_group_group_id FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_group_membership_user_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    training_session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_attending boolean NOT NULL,
    reason text,
    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_attendance_training_session_training_session_id FOREIGN KEY (training_session_id) REFERENCES training_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_user_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX ix_attendance_training_session_id ON attendance (training_session_id);

CREATE INDEX ix_attendance_user_id ON attendance (user_id);

CREATE INDEX ix_group_sport_id ON "group" (sport_id);

CREATE INDEX ix_sport_search_vector ON sport USING GIN (search_vector);

CREATE INDEX ix_training_session_group_id ON training_session (group_id);

CREATE UNIQUE INDEX ix_user_email ON "user" (email);

CREATE UNIQUE INDEX ix_user_phone_number ON "user" (phone_number);

CREATE INDEX ix_user_group_membership_group_id ON user_group_membership (group_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250413171257_Initial', '9.0.3');

COMMIT;

