CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE club (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    CONSTRAINT pk_club PRIMARY KEY (id)
);

CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    display_name text NOT NULL,
    email character varying(255),
    phone_number text,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE club_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    club_id bigint NOT NULL,
    role_name text NOT NULL,
    permissions_json text,
    CONSTRAINT pk_club_role PRIMARY KEY (id),
    CONSTRAINT fk_club_role_club_club_id FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE CASCADE
);

CREATE TABLE department (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_name text NOT NULL,
    description text,
    club_id bigint NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT fk_department_club_club_id FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE CASCADE
);

CREATE TABLE user_club_membership (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    club_id bigint NOT NULL,
    CONSTRAINT pk_user_club_membership PRIMARY KEY (id),
    CONSTRAINT fk_user_club_membership_club_club_id FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_club_membership_user_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE department_kpi (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_id bigint NOT NULL,
    name text NOT NULL,
    description text,
    CONSTRAINT pk_department_kpi PRIMARY KEY (id),
    CONSTRAINT fk_department_kpi_department_department_id FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE
);

CREATE TABLE "group" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    group_name text NOT NULL,
    description text,
    department_id bigint NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (id),
    CONSTRAINT fk_group_department_department_id FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE
);

CREATE TABLE membership_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_club_membership_id bigint NOT NULL,
    club_role_id bigint NOT NULL,
    CONSTRAINT pk_membership_role PRIMARY KEY (id),
    CONSTRAINT fk_membership_role_club_role_club_role_id FOREIGN KEY (club_role_id) REFERENCES club_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_role_user_club_membership_user_club_membership_id FOREIGN KEY (user_club_membership_id) REFERENCES user_club_membership (id) ON DELETE CASCADE
);

CREATE TABLE group_kpi (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    group_id bigint NOT NULL,
    department_kpi_id bigint,
    name text NOT NULL,
    description text,
    CONSTRAINT pk_group_kpi PRIMARY KEY (id),
    CONSTRAINT fk_group_kpi_department_kpi_department_kpi_id FOREIGN KEY (department_kpi_id) REFERENCES department_kpi (id),
    CONSTRAINT fk_group_kpi_group_group_id FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE
);

CREATE TABLE option (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    type integer NOT NULL,
    name text NOT NULL,
    value text,
    club_id bigint,
    department_id bigint,
    group_id bigint,
    CONSTRAINT pk_option PRIMARY KEY (id),
    CONSTRAINT fk_option_club_club_id FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE RESTRICT,
    CONSTRAINT fk_option_department_department_id FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE RESTRICT,
    CONSTRAINT fk_option_group_group_id FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE RESTRICT
);

CREATE TABLE training_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    session_date timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    location text,
    group_id bigint NOT NULL,
    CONSTRAINT pk_training_session PRIMARY KEY (id),
    CONSTRAINT fk_training_session_group_group_id FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE
);

CREATE TABLE user_group_kpi_value (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    group_kpi_id bigint NOT NULL,
    user_id bigint NOT NULL,
    int_value integer NOT NULL,
    text_value text,
    CONSTRAINT pk_user_group_kpi_value PRIMARY KEY (id),
    CONSTRAINT fk_user_group_kpi_value_group_kpi_group_kpi_id FOREIGN KEY (group_kpi_id) REFERENCES group_kpi (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_group_kpi_value_user_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    training_session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_attending boolean NOT NULL,
    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_attendance_training_session_training_session_id FOREIGN KEY (training_session_id) REFERENCES training_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_user_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX ix_attendance_training_session_id ON attendance (training_session_id);

CREATE INDEX ix_attendance_user_id ON attendance (user_id);

CREATE INDEX ix_club_role_club_id ON club_role (club_id);

CREATE INDEX ix_department_club_id ON department (club_id);

CREATE INDEX ix_department_kpi_department_id ON department_kpi (department_id);

CREATE INDEX ix_group_department_id ON "group" (department_id);

CREATE INDEX ix_group_kpi_department_kpi_id ON group_kpi (department_kpi_id);

CREATE INDEX ix_group_kpi_group_id ON group_kpi (group_id);

CREATE INDEX ix_membership_role_club_role_id ON membership_role (club_role_id);

CREATE INDEX ix_membership_role_user_club_membership_id ON membership_role (user_club_membership_id);

CREATE INDEX ix_option_club_id ON option (club_id);

CREATE INDEX ix_option_department_id ON option (department_id);

CREATE INDEX ix_option_group_id ON option (group_id);

CREATE INDEX ix_training_session_group_id ON training_session (group_id);

CREATE UNIQUE INDEX ix_user_email ON "user" (email);

CREATE UNIQUE INDEX ix_user_phone_number ON "user" (phone_number);

CREATE INDEX ix_user_club_membership_club_id ON user_club_membership (club_id);

CREATE INDEX ix_user_club_membership_user_id ON user_club_membership (user_id);

CREATE INDEX ix_user_group_kpi_value_group_kpi_id ON user_group_kpi_value (group_kpi_id);

CREATE INDEX ix_user_group_kpi_value_user_id ON user_group_kpi_value (user_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250315125730_Initial', '9.0.2');

COMMIT;

